FROM debian:jessie
MAINTAINER Bill Morrison <bill.morrison@teamsolutionz.com>

# install extensions
# RUN requirements="git vim sudo python" \
#     && apt-get update && apt-get install -y $requirements
    
# Add the dirs and set permissions
RUN mkdir -p /var/versions/version-
